config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: [:index]
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: 'pages#home'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end
  resources :users do
    resource :profile
  end

  resources :chatrooms do
    resource :requests
    resource :chatroom_users
    resources :messages
  end
end

app/models/chatroom.rb
# frozen_string_literal: true

# This class defines a chatroom, which has chatroom users, requests, and messages.

class Chatroom < ApplicationRecord
  has_many :chatroom_users
  has_many :users, through: :chatroom_users
  has_many :requests
  has_many :messages
  validates :title, presence: true
end

app/controllers/chatrooms_controller.rb
# frozen_string_literal: true

# This class creates, displays, and finds chatrooms.

class ChatroomsController < ApplicationController
  # Finds all chatrooms where the current user is a member.
  def index
    @user = User.find(current_user.id)
    current_user.profile&.update_attribute(:search, '')
    @chatrooms = Chatroom.all
  end

  # Finds and displays the chatroom with the given parameters, along with its messages.
  def show
    @user = User.find(current_user.id)
    current_user.profile&.update_attribute(:search, '')
    @chatroom = Chatroom.find(params[:id])

    @chatroom_user = @chatroom.chatroom_users.where(user_id: current_user.id).first
    @chatroom_user&.update_attribute(:read, true)
    @messages = @chatroom.messages.order(created_at: :desc).reverse
  end

  # Updates the chatroom with the given parameters and redirects to the chatroom if successful.
  def update
    @user = User.find(current_user.id)
    @chatroom = Chatroom.find(params[:chatroom_id])
    if @chatroom.update_attributes(chatroom_params)
      redirect_to user_path(id: params[:user_id])
    end
  end

  # Creates a new chatroom.
  def new
    @user = User.find(current_user.id)
    current_user.profile&.update_attribute(:search, '')
    @chatroom = Chatroom.new
  end

  # Edits a chatroom. Not currently implemented or used.
  def edit; end

  # Creates a new chatroom and redirects to it if successfully saved.
  def create
    @user = User.find(current_user.id)
    @chatroom = Chatroom.new(chatroom_params)
    if @chatroom.save
      redirect_to chatroom_chatroom_users_path(chatroom_id: @chatroom.id, user_id: current_user.id), method: :post
    else
      render action: new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.

  # Never trust parameters from the scary internet, only allow the white list through.
  def chatroom_params
    params.require(:chatroom).permit(:title, :details, :search, :gender, :collegestudent, :minimumage, :maximumage, :city, :visible)
  end
end

app/views/chatrooms/edit.html.erb
<body style="background-color:#FFFAFA">
  <div class="fluid-container">
    <div id="wrapper">
      <div class="post-content">
        
        <h4>Edit Post</h4><br>
        <%= render 'form' %>
        
      </div>
    </div>
  </div>
</body>

app/views/chatrooms/index.html.erb
<div class="container fluid">
	<div class="row">
		<div class="col-sm-4">
			<% if user_signed_in? %>
				<h5 class="title">Groups</h5>
				<ul>
					<% current_user.chatrooms.each do |chatroom| %>
						<% @currentchatroomuser = chatroom.chatroom_users.where(user_id: current_user.id).first %>
						<% if @currentchatroomuser.read == true %>
							<li><%= link_to chatroom.title, chatroom %><br>
						<% else %>
							<li><b><%= link_to chatroom.title, chatroom %></b><br></li>
						<% end %>
						<%= link_to 'Leave', chatroom_chatroom_users_path(chatroom_id: chatroom.id, user_id: current_user.id), method: :delete %></li>
					
					<%end%>
				</ul>
			<% end %>
		</div>
		<div class="col-sm-4">
			<% if user_signed_in? %>
				<h5 class="title">Requests</h5>
				<ul>
					<% current_user.chatrooms.each do |x| %>
						
						<% x.requests.order("created_at DESC").each do |t| %>
							<%if !x.chatroom_users.exists?(user_id: t.user_id)%>
								<% @chatroom_user = ChatroomUser.find_by user_id: current_user.id, chatroom_id: x.id %>
								<% if @chatroom_user.admin == true %>
								<li><% @conversationrequest = User.find(t.user_id) %><% @conversationrequest = User.find(@conversationrequest.id) %>
								<div class="post-image">
      	         					<%= image_tag @conversationrequest.profile.avatar.url(:medium) %>
      	         				</div>&nbsp;
								<%= link_to @conversationrequest.profile.first_name, user_path(:id => @conversationrequest.id) %>&nbsp;has requested to join&nbsp;<%= x.title %></li>
								
								<% temporarystring = 'Accept '+@conversationrequest.profile.first_name%>
								<%= link_to temporarystring, chatroom_chatroom_users_path(request_id: t.id, chatroom_id: x.id), method: :post%><br>
							
								<%= link_to 'Delete Request', chatroom_requests_path(chatroom_id: x.id, request_id: t.id), method: :delete%>
							
								<%end%>
							<%end%>
						<%end%>
					<%end%>
											
							
							
						
				</ul>
			<% end %>
		</div>
		<div class="col-sm-4">
			<% if user_signed_in? %>
				<h5 class="title">Your Requests</h5>
				<ul>
					<% current_user.requests.each do |x| %>
						<% @conversation = Chatroom.find(x.chatroom_id) %>
						<% if !@conversation.chatroom_users.exists?(user_id: current_user.id)%>
						<li>You have requested to join&nbsp;<%=@conversation.title%></li>
						<% end %>
					
					<%end%>
				</ul>
			<%end%>
					
		</div>
	  
	</div>
</div>

app/views/chatrooms/new.html.erb
<div class="fluid-container">
<body style="background-color:#FFFAFA">
  <div id="wrapper">
    <div class="post-content">
      <div>
        <h4>Create Post</h4><br>
        <%= render 'form' %>
      </div>
    </div>
  </div>
</body>
</div>

app/views/chatrooms/show.html.erb
<div class="fluid-container">
	<div class="row">
		<% if @chatroom.chatroom_users.exists?(user_id: current_user.id) %>
		<div class="col-sm-2">
			<% if user_signed_in? %>
				<h5 class="title">Conversations</h5>
				<ul>
					<% current_user.chatrooms.each do |chatroom| %>
						<% @currentchatroomuser = chatroom.chatroom_users.where(user_id: current_user.id).first %>
						<% if @currentchatroomuser.read == true %>
							<li><%= link_to chatroom.title, chatroom %><br>
						<% else %>
							<li><b><%= link_to chatroom.title, chatroom %></b><br></li>
						<% end %>
						<%= link_to 'Leave', chatroom_chatroom_users_path(chatroom_id: @chatroom.id, user_id: current_user.id), method: :delete %></li>
					<%end%>
				</ul>
			<% end %>
		</div>
		<% end%>
		
	  <div class="col-sm-8">
      <p>
        <strong>Title:&nbsp;</strong>
        <%= @chatroom.title %><br>
        <% if !@chatroom.details.blank? %>
        <strong>Details:&nbsp;</strong>
        <%= @chatroom.details %>
        <% end %>
      </p>
      <% if @chatroom.chatroom_users.exists?(user_id: current_user.id) %>
      <div data-behavior='messages'>
        <% @messages.each do |message| %>
        	<div><strong><%= message.user.profile.first_name %>:&nbsp;</strong><%= message.body %></div>
        <%end%>
      </div>
      <%= form_for [@chatroom, Message.new], url: chatroom_messages_path(chatroom_id: @chatroom.id, user_id: current_user.id), method: :post, remote: true do |f| %>
        <%= f.text_area :body, rows: 1, class: "form-control", autofocus: true  %>
        <%= f.submit 'Send', class: 'btn btn-default', class: 'bu' %>
      <% end %>
      <% end %>
	  </div>
	  <div class="col-sm-2">
	 	
	  <% if @chatroom.chatroom_users.exists?(user_id: current_user.id) %><div class="col-sm-2"><%end%>
			<% if user_signed_in? %>
				<h5 class="title">Members</h5>
				<ul>
					<% @chatroom.chatroom_users.each do |x| %>
						<% @conversationmember = User.find(x.user_id) %> <% @conversationmember = User.find(@conversationmember.id) %>
						<div class="post-image">
      					<li><%= image_tag @conversationmember.profile.avatar.url(:medium) %>
      	    			</div>
						<%= link_to @conversationmember.profile.first_name, user_path(:id => @conversationmember.id) %>&nbsp;|&nbsp;<%=@conversationmember.profile.age%>
						</li><br>
					
					
					
					<%end%>
				</ul>
	
				<% if @chatroom.chatroom_users.exists?(user_id: current_user.id) %>
				<h5 class="title"><%=@chatroom.requests.count%>&nbsp;request(s)</h5>
				<% end %>
				
			<% end %>
		</div>
		
	</div>
</div>