config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: [:index]
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: 'pages#home'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end
  resources :users do
    resource :profile
  end

  resources :chatrooms do
    resource :requests
    resource :chatroom_users
    resources :messages
  end
end

app/models/user.rb
# frozen_string_literal: true

# This class defines a user, which has a profile, chatroom, chatroom users, messages, and requests.

class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :profile
  has_many :chatroom_users
  has_many :chatrooms, through: :chatroom_users
  has_many :messages
  has_many :requests
end

app/controllers/users_controller.rb
# frozen_string_literal: true

# This class finds the user with the given ID.

class UsersController < ApplicationController
  before_action :authenticate_user!
  # Find the user with the given ID.
  def show
    @user = User.find(params[:id])
  end
end

app/views/users/show.html.erb
<!DOCTYPE html>

<header>
	<div class="fluid-container" style="margin-top: 70px">
		<div class = "profile">
			<div class="profile-image">
				<%= image_tag @user.profile.avatar.url(:medium) %>		
			</div>
				<div class="profile-user-name"><%= @user.profile.first_name %></div>&nbsp;
				<div class="profile-user-name"><%= @user.profile.last_name %></div>
				<% if current_user==@user %>
				<button class="profile-edit-btn">
						<%= link_to "Edit Profile", edit_user_profile_path(@user), class: "buttonprofile"%>
				</button>
				<%end%>
		</div>
		
		</div>
		
	</div>`
</header>