config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :cities, only: [:index]
  devise_for :users
  devise_scope :user do
    authenticated :user do
      root to: 'pages#home'
    end
    unauthenticated :user do
      root to: 'devise/registrations#new', as: :unauthenticated_root
    end
  end
  resources :users do
    resource :profile
  end

  resources :chatrooms do
    resource :requests
    resource :chatroom_users
    resources :messages
  end
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(object.errors.count, 'error') %>.</strong></p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans:400,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat&display=swap" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    
      <body style="background-color:#FFFAFA">
        <% unless (controller_name=="sessions" && action_name=='new') || (controller_name=="registrations" && action_name=='new') || (controller_name=="passwords" && action_name=='new') %>
        
          <nav class="navbar navbar-default navbar-static-top" role="navigation">
            <div class='container'>
              <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#main-nav-collapse">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                
                
               
            
                <%= link_to root_path, class: "navbar-brand" do %>
                    pangaea
                <% end %>
              </div>
            <div class="collapse navbar-collapse" id="main-nav-collapse">
              <div class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                  <li><%= link_to "Log Out", destroy_user_session_path, method: :delete%></li>
                <% else %>
                  <li><%= link_to "Log In", new_user_session_path, class: "linkfocus"%></li>
                  <li><%= link_to "Sign Up", new_user_registration_path, class: "linkfocus"%></li>
                <% end %>
              </div>
              <ul class="nav navbar-nav navbar-right">
                
                <% if user_signed_in? %>
                  <% if current_user.profile %>
                    <li><%= form_for current_user.profile, url: user_profile_path(user_id: current_user.id) do |f| %>
                    <p>
                    <%= f.text_field :search, autocomplete: "off", placeholder: "Try \"Tennis\"", class: 'searchbar' %>
                    <button type="submit"><i class="fa fa-search"></i>
                    <% end %></li>
                    <li><%= link_to "Create Post", new_chatroom_path(user_id: current_user.id), class: "navbar-brand" %></li>
                    <li><%= link_to "Groups", chatrooms_path(user_id: current_user.id), class: "navbar-brand" %></li>
                    <li><%= link_to "Profile", user_path(:id => current_user.id), class: "navbar-brand" %></li>
                    <% else %>
                    <li><%= link_to "Create Profile", new_user_profile_path(user_id: current_user.id)%></li>
                  <% end %>
                <% end %>
              </ul>
              
            </div><!-- /.navbar-collapse -->
          </div>
        
      </nav>
      <% end %>
      <div class="container">
      
      <%= yield %>
      </div>
    </body>
  
</html>